apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  labels:
    io.kompose.service: harvester
  name: harvester
spec:
  selector:
    matchLabels:
      io.kompose.service: harvester
  template:
    metadata:
      labels:
        io.kompose.service: harvester
    spec:
      containers:
        - image: file
          name: file
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers