apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
  - name: "6689"
    port: 6689
    targetPort: 6689
  - name: "6688"
    port: 6688
    targetPort: 6688
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
